name: Hymys Test
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2395
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6db0fe'
    - '#1b2b29'
    - '#69862c'
    - '#afa790'
    - '#f0e6d4'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
