name: Hymys Test
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48876
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0c0c16'
    - '#3f4255'
    - '#c8cdd1'
    - '#9099a2'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
