name: Hymys Test
favicon: null
layout_spectrum: 0.17841
typography_spectrum: 0.48876
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#008fa5'
    - '#b7dfe5'
    - '#2fa4b5'
    - '#7fc7d2'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
